pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

Singleton {
    property alias color: jsonAdapter.color
    property alias palette: jsonAdapter.palette
    property list<string> colors: ["background", "error", "error_container", "inverse_on_surface", "inverse_primary", "inverse_surface", "on_background", "on_error", "on_error_container", "on_primary", "on_primary_container", "on_primary_fixed", "on_primary_fixed_variant", "on_secondary", "on_secondary_container", "on_secondary_fixed", "on_secondary_fixed_variant", "on_surface", "on_surface_variant", "on_tertiary", "on_tertiary_container", "on_tertiary_fixed", "on_tertiary_fixed_variant", "outline", "outline_variant", "primary", "primary_container", "primary_fixed", "primary_fixed_dim", "scrim", "secondary", "secondary_container", "secondary_fixed", "secondary_fixed_dim", "shadow", "surface", "surface_bright", "surface_container", "surface_container_high", "surface_container_highest", "surface_container_low", "surface_container_lowest", "surface_dim", "surface_tint", "surface_variant", "tertiary", "tertiary_container", "tertiary_fixed", "tertiary_fixed_dim"]
    property list<string> palettes: ["error0", "error5", "error10", "error15", "error20", "error25", "error30", "error35", "error40", "error50", "error60", "error70", "error80", "error90", "error95", "error98", "error99", "error100", "neutral0", "neutral5", "neutral10", "neutral15", "neutral20", "neutral25", "neutral30", "neutral35", "neutral40", "neutral50", "neutral60", "neutral70", "neutral80", "neutral90", "neutral95", "neutral98", "neutral99", "neutral100", "neutral_variant0", "neutral_variant5", "neutral_variant10", "neutral_variant15", "neutral_variant20", "neutral_variant25", "neutral_variant30", "neutral_variant35", "neutral_variant40", "neutral_variant50", "neutral_variant60", "neutral_variant70", "neutral_variant80", "neutral_variant90", "neutral_variant95", "neutral_variant98", "neutral_variant99", "neutral_variant100", "primary0", "primary5", "primary10", "primary15", "primary20", "primary25", "primary30", "primary35", "primary40", "primary50", "primary60", "primary70", "primary80", "primary90", "primary95", "primary98", "primary99", "primary100", "secondary0", "secondary5", "secondary10", "secondary15", "secondary20", "secondary25", "secondary30", "secondary35", "secondary40", "secondary50", "secondary60", "secondary70", "secondary80", "secondary90", "secondary95", "secondary98", "secondary99", "secondary100", "tertiary0", "tertiary5", "tertiary10", "tertiary15", "tertiary20", "tertiary25", "tertiary30", "tertiary35", "tertiary40", "tertiary50", "tertiary60", "tertiary70", "tertiary80", "tertiary90", "tertiary95", "tertiary98", "tertiary99", "tertiary100"]
    FileView {
        path: Qt.resolvedUrl("colors.json")
        watchChanges: true
        onFileChanged: reload()

        JsonAdapter {
            id: jsonAdapter

            readonly property Color color: Color {}
            readonly property Palette palette: Palette {}
        }
    }

    component Color: JsonObject {
        property color background: "transparent"
        property color error: "transparent"
        property color error_container: "transparent"
        property color inverse_on_surface: "transparent"
        property color inverse_primary: "transparent"
        property color inverse_surface: "transparent"
        property color on_background: "transparent"
        property color on_error: "transparent"
        property color on_error_container: "transparent"
        property color on_primary: "transparent"
        property color on_primary_container: "transparent"
        property color on_primary_fixed: "transparent"
        property color on_primary_fixed_variant: "transparent"
        property color on_secondary: "transparent"
        property color on_secondary_container: "transparent"
        property color on_secondary_fixed: "transparent"
        property color on_secondary_fixed_variant: "transparent"
        property color on_surface: "transparent"
        property color on_surface_variant: "transparent"
        property color on_tertiary: "transparent"
        property color on_tertiary_container: "transparent"
        property color on_tertiary_fixed: "transparent"
        property color on_tertiary_fixed_variant: "transparent"
        property color outline: "transparent"
        property color outline_variant: "transparent"
        property color primary: "transparent"
        property color primary_container: "transparent"
        property color primary_fixed: "transparent"
        property color primary_fixed_dim: "transparent"
        property color scrim: "transparent"
        property color secondary: "transparent"
        property color secondary_container: "transparent"
        property color secondary_fixed: "transparent"
        property color secondary_fixed_dim: "transparent"
        property color shadow: "transparent"
        property color surface: "transparent"
        property color surface_bright: "transparent"
        property color surface_container: "transparent"
        property color surface_container_high: "transparent"
        property color surface_container_highest: "transparent"
        property color surface_container_low: "transparent"
        property color surface_container_lowest: "transparent"
        property color surface_dim: "transparent"
        property color surface_tint: "transparent"
        property color surface_variant: "transparent"
        property color tertiary: "transparent"
        property color tertiary_container: "transparent"
        property color tertiary_fixed: "transparent"
        property color tertiary_fixed_dim: "transparent"
    }

    component Palette: JsonObject {
        property color error0: "transparent"
        property color error5: "transparent"
        property color error10: "transparent"
        property color error15: "transparent"
        property color error20: "transparent"
        property color error25: "transparent"
        property color error30: "transparent"
        property color error35: "transparent"
        property color error40: "transparent"
        property color error50: "transparent"
        property color error60: "transparent"
        property color error70: "transparent"
        property color error80: "transparent"
        property color error90: "transparent"
        property color error95: "transparent"
        property color error98: "transparent"
        property color error99: "transparent"
        property color error100: "transparent"

        property color neutral0: "transparent"
        property color neutral5: "transparent"
        property color neutral10: "transparent"
        property color neutral15: "transparent"
        property color neutral20: "transparent"
        property color neutral25: "transparent"
        property color neutral30: "transparent"
        property color neutral35: "transparent"
        property color neutral40: "transparent"
        property color neutral50: "transparent"
        property color neutral60: "transparent"
        property color neutral70: "transparent"
        property color neutral80: "transparent"
        property color neutral90: "transparent"
        property color neutral95: "transparent"
        property color neutral98: "transparent"
        property color neutral99: "transparent"
        property color neutral100: "transparent"

        property color neutral_variant0: "transparent"
        property color neutral_variant5: "transparent"
        property color neutral_variant10: "transparent"
        property color neutral_variant15: "transparent"
        property color neutral_variant20: "transparent"
        property color neutral_variant25: "transparent"
        property color neutral_variant30: "transparent"
        property color neutral_variant35: "transparent"
        property color neutral_variant40: "transparent"
        property color neutral_variant50: "transparent"
        property color neutral_variant60: "transparent"
        property color neutral_variant70: "transparent"
        property color neutral_variant80: "transparent"
        property color neutral_variant90: "transparent"
        property color neutral_variant95: "transparent"
        property color neutral_variant98: "transparent"
        property color neutral_variant99: "transparent"
        property color neutral_variant100: "transparent"

        property color primary0: "transparent"
        property color primary5: "transparent"
        property color primary10: "transparent"
        property color primary15: "transparent"
        property color primary20: "transparent"
        property color primary25: "transparent"
        property color primary30: "transparent"
        property color primary35: "transparent"
        property color primary40: "transparent"
        property color primary50: "transparent"
        property color primary60: "transparent"
        property color primary70: "transparent"
        property color primary80: "transparent"
        property color primary90: "transparent"
        property color primary95: "transparent"
        property color primary98: "transparent"
        property color primary99: "transparent"
        property color primary100: "transparent"

        property color secondary0: "transparent"
        property color secondary5: "transparent"
        property color secondary10: "transparent"
        property color secondary15: "transparent"
        property color secondary20: "transparent"
        property color secondary25: "transparent"
        property color secondary30: "transparent"
        property color secondary35: "transparent"
        property color secondary40: "transparent"
        property color secondary50: "transparent"
        property color secondary60: "transparent"
        property color secondary70: "transparent"
        property color secondary80: "transparent"
        property color secondary90: "transparent"
        property color secondary95: "transparent"
        property color secondary98: "transparent"
        property color secondary99: "transparent"
        property color secondary100: "transparent"

        property color tertiary0: "transparent"
        property color tertiary5: "transparent"
        property color tertiary10: "transparent"
        property color tertiary15: "transparent"
        property color tertiary20: "transparent"
        property color tertiary25: "transparent"
        property color tertiary30: "transparent"
        property color tertiary35: "transparent"
        property color tertiary40: "transparent"
        property color tertiary50: "transparent"
        property color tertiary60: "transparent"
        property color tertiary70: "transparent"
        property color tertiary80: "transparent"
        property color tertiary90: "transparent"
        property color tertiary95: "transparent"
        property color tertiary98: "transparent"
        property color tertiary99: "transparent"
        property color tertiary100: "transparent"
    }
}
