
$background = rgb(1E1C1B)
$foreground = rgb(F3F4EF)
$color0 = rgb(454341)
$color1 = rgb(7D746B)
$color2 = rgb(837A8F)
$color3 = rgb(4A88A0)
$color4 = rgb(6A8C74)
$color5 = rgb(948E50)
$color6 = rgb(A6A79D)
$color7 = rgb(E6E7E0)
$color8 = rgb(A1A19C)
$color9 = rgb(A79B8F)
$color10 = rgb(AFA2BF)
$color11 = rgb(62B6D5)
$color12 = rgb(8DBA9A)
$color13 = rgb(C5BD6A)
$color14 = rgb(DDDFD1)
$color15 = rgb(E6E7E0)
