#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ./Config/env.conf

#################
### AUTOSTART ###
#################

source = ./Config/autostart.conf

################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
source = ./monitors.conf

###################
### MY PROGRAMS ###
###################

source = ./Config/programs.conf

###################
### PERMISSIONS ###
###################

# source = ./Config/permisions.conf

#####################
### LOOK AND FEEL ###
#####################

source = ./Config/theme.conf

#############
### INPUT ###
#############

# Add input config here if needed

#############
### Rules ###
#############

source = ./Config/rules.conf

###################
### KEYBINDINGS ###
###################

source = ./Config/keybinds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ./Config/workflows.conf
source = ./Config/workspaces.conf
