require("conform").setup({
	formatters_by_ft = {
		lua = { "stylua" },
		qml = { "qmlformat" },
		nix = { "alejandra" },
		javascript = { "prettierd", "prettier" },
		javascriptreact = { "prettierd", "prettier" },
		typescript = { "prettierd", "prettier" },
		typescriptreact = { "prettierd", "prettier" },
		vue = { "prettierd", "prettier" },
		svelte = { "prettierd", "prettier" },
		css = { "prettierd", "prettier" },
		scss = { "prettierd", "prettier" },
		less = { "prettierd", "prettier" },
		html = { "prettierd", "prettier" },
		json = { "prettierd", "prettier" },
		jsonc = { "prettierd", "prettier" },
		yaml = { "prettierd", "prettier" },
		markdown = { "prettierd", "prettier" },
		graphql = { "prettierd", "prettier" },
		rust = { "rustfmt" },
		ron = { "ronfmt" },
		sh = { "shfmt" },
		bash = { "shfmt" },
		toml = { "taplo" },
	},
	format_on_save = {
		timeout_ms = 500,
		lsp_fallback = true,
	},
	formatters = {
		qmlformat = {
			command = "qmlformat",
			stdin = false,
		},
		ronfmt = {
			command = "ronfmt",
			stdin = false,
			args = { "$FILENAME" },
		},
	},
})
