-- Generated by Matugen (themed)

require("mini.hues").setup({
  background = "{{ colors.surface }}",
  foreground = "{{ colors.on_surface }}",
})

local function set_hl(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

set_hl({ "Type", "TSType", "@type" }, {
  fg = "{{ colors.tertiary }}",
})

set_hl({ "String", "TSString" }, {
  fg = "{{ colors.tertiary }}",
})

set_hl({ "TSComment", "Comment" }, {
  fg = "{{ colors.outline }}",
  italic = true,
})

set_hl({ "TSMethod", "Method" }, {
  fg = "{{ colors.tertiary }}",
})

set_hl({ "TSFunction", "Function" }, {
  fg = "{{ colors.secondary }}",
})

set_hl({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
  fg = "{{ colors.primary }}",
})

local function set_bg(groups, bg)
  for _, group in pairs(groups) do
    vim.api.nvim_set_hl(0, group, { bg = bg })
  end
end

set_bg({
  "Normal", "NormalNC", "SignColumn", "LineNr",
  "EndOfBuffer", "StatusLine", "StatusLineNC", "lualine",
}, "{{ colors.surface }}")

-- Bufferline
local function set_bufferline_highlights()
  local ok, bufferline = pcall(require, "bufferline")
  if ok then
    bufferline.setup({
      highlights = {
        fill = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
        background = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
        buffer_visible = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface }}" },
        separator = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.outline }}" },
        buffer_selected = {
          bg = "{{ colors.surface }}",
          fg = "{{ colors.tertiary }}",
          bold = true,
        },
      },
    })
  end
end

vim.defer_fn(set_bufferline_highlights, 100)
vim.api.nvim_create_autocmd("ColorScheme", {
  pattern = "*",
  callback = set_bufferline_highlights,
})

-- Lualine theme
local lualine_theme = {
  normal = {
    a = { bg = "{{ colors.primary }}", fg = "{{ colors.on_primary }}", gui = "bold" },
    b = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface }}" },
    c = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
  },
  insert = {
    a = { bg = "{{ colors.secondary }}", fg = "{{ colors.on_secondary }}", gui = "bold" },
    b = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface }}" },
    c = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
  },
  visual = {
    a = { bg = "{{ colors.tertiary }}", fg = "{{ colors.on_tertiary }}", gui = "bold" },
    b = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface }}" },
    c = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
  },
  replace = {
    a = { bg = "{{ colors.error }}", fg = "{{ colors.on_error }}", gui = "bold" },
    b = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface }}" },
    c = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
  },
  command = {
    a = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface_variant }}", gui = "bold" },
    b = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface }}" },
    c = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
  },
  inactive = {
    a = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.outline }}", gui = "bold" },
    b = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.outline }}" },
    c = { bg = "{{ colors.surface }}", fg = "{{ colors.outline }}" },
  },
}

require("lualine").setup({
  options = { theme = lualine_theme },
})
