-- Generated by Matugen

require("mini.hues").setup({
	background = "{{colors.background.default.hex}}",
	foreground = "{{colors.on_surface.default.hex}}",
})

-- Custom overrides on top of mini.hues defaults

local function set_hl(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- mini.hues sets Type/ @type same as foreground, making type names invisible
set_hl({ "Type", "TSType", "@type" }, {
	fg = "{{colors.tertiary_container.default.hex}}",
})

-- Make strings contrast better
set_hl({ "String", "TSString" }, {
	fg = "{{colors.tertiary.default.hex | lighten: -15.0 }}",
})

-- Grey out comments
set_hl({ "TSComment", "Comment" }, {
	fg = "{{colors.outline.default.hex}}",
	italic = true,
})

set_hl({ "TSMethod", "Method" }, {
	fg = "{{colors.tertiary.default.hex}}",
})

set_hl({ "TSFunction", "Function" }, {
	fg = "{{colors.secondary.default.hex}}",
})

set_hl({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "{{colors.inverse_primary.default.hex}}",
})

-- Explicit backgrounds for visibility without transparency
local function set_bg(groups, bg)
	for _, group in pairs(groups) do
		vim.api.nvim_set_hl(0, group, { bg = bg })
	end
end

set_bg({
	"Normal",
	"NormalNC",
	"SignColumn",
	"LineNr",
	"EndOfBuffer",
	"StatusLine",
	"StatusLineNC",
	"lualine",
}, "{{colors.background.default.hex}}")

-- Bufferline (tab) colors
local function set_bufferline_highlights()
	local ok, bufferline = pcall(require, "bufferline")
	if ok then
		bufferline.setup({
			highlights = {
				fill = { bg = "{{colors.background.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
				background = { bg = "{{colors.background.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
				buffer_visible = {
					bg = "{{colors.surface_container_low.default.hex}}",
					fg = "{{colors.on_surface.default.hex}}",
				},
				separator = {
					bg = "{{colors.surface_container_low.default.hex}}",
					fg = "{{colors.outline_variant.default.hex}}",
				},
				buffer_selected = {
					bg = "{{colors.surface_container_lowest.default.hex}}",
					fg = "{{colors.tertiary.default.hex}}",
					bold = true,
				},
			},
		})
	end
end

vim.defer_fn(set_bufferline_highlights, 100)
vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "*",
	callback = set_bufferline_highlights,
})

-- Snacks.nvim highlights
local function set_snacks_highlights()
	set_hl({
		"SnacksPicker",
		"SnacksPickerList",
		"SnacksPickerPreview",
		"SnacksPickerInput",
		"SnacksPickerBox",
	}, {
		bg = "{{colors.surface_container_low.default.hex}}",
	})

	set_hl({
		"SnacksPickerBorder",
		"SnacksPickerInputBorder",
		"SnacksPickerPreviewBorder",
		"SnacksPickerListBorder",
		"SnacksPickerBoxBorder",
	}, {
		fg = "{{colors.outline.default.hex}}",
		bg = "{{colors.background.default.hex}}",
	})

	set_hl({
		"SnacksInputNormal",
		"SnacksInput",
	}, {
		bg = "{{colors.surface_container_low.default.hex}}",
		fg = "{{colors.on_surface.default.hex}}",
	})

	set_hl({
		"SnacksInputBorder",
		"SnacksPickerInputBorder",
	}, {
		fg = "{{colors.outline.default.hex}}",
		bg = "{{colors.background.default.hex}}",
	})

	set_hl({
		"SnacksInputTitle",
		"SnacksPickerInputTitle",
	}, {
		fg = "{{colors.primary.default.hex}}",
		bg = "{{colors.background.default.hex}}",
	})

	set_hl({
		"SnacksInputIcon",
	}, {
		fg = "{{colors.primary.default.hex}}",
	})

	set_hl({
		"SnacksPickerInputSearch",
	}, {
		fg = "{{colors.primary.default.hex}}",
	})

	set_hl({
		"SnacksPickerTotals",
		"SnacksPickerSpinner",
	}, {
		fg = "{{colors.outline.default.hex}}",
	})

	set_hl({
		"SnacksPickerLabel",
		"SnacksPickerSpecial",
	}, {
		fg = "{{colors.secondary.default.hex}}",
	})

	set_hl({
		"SnacksPickerSelected",
	}, {
		fg = "{{colors.primary.default.hex}}",
		bold = true,
	})

	set_hl({
		"SnacksPickerPrompt",
		"SnacksPickerMatch",
	}, {
		fg = "{{colors.primary.default.hex}}",
	})

	set_hl({
		"SnacksPickerDir",
	}, {
		fg = "{{colors.on_surface_variant.default.hex}}",
	})

	set_hl({
		"SnacksIndent",
		"SnacksIndentBlank",
	}, {
		fg = "{{colors.outline_variant.default.hex}}",
	})

	set_hl({
		"SnacksIndentScope",
		"SnacksIndentChunk",
	}, {
		fg = "{{colors.primary.default.hex}}",
	})

	set_hl({
		"SnacksNotifierInfo",
		"SnacksNotifierTitleInfo",
		"SnacksNotifierIconInfo",
	}, {
		fg = "{{colors.primary.default.hex}}",
	})

	set_hl({
		"SnacksNotifierWarn",
		"SnacksNotifierTitleWarn",
		"SnacksNotifierIconWarn",
	}, {
		fg = "{{colors.tertiary.default.hex}}",
	})

	set_hl({
		"SnacksNotifierError",
		"SnacksNotifierTitleError",
		"SnacksNotifierIconError",
	}, {
		fg = "{{colors.error.default.hex}}",
	})

	set_hl({
		"SnacksNotifierDebug",
		"SnacksNotifierTitleDebug",
		"SnacksNotifierIconDebug",
	}, {
		fg = "{{colors.outline.default.hex}}",
	})

	set_hl({
		"SnacksNotifierTrace",
		"SnacksNotifierTitleTrace",
		"SnacksNotifierIconTrace",
	}, {
		fg = "{{colors.secondary.default.hex}}",
	})

	set_hl({
		"SnacksNotifierHistory",
		"SnacksNotifierHistoryTitle",
		"SnacksNotifierHistoryDateTime",
		"SnacksNotifierHistoryType",
	}, {
		fg = "{{colors.on_surface_variant.default.hex}}",
	})

	set_hl({
		"SnacksDashboardHeader",
		"SnacksDashboardFooter",
	}, {
		fg = "{{colors.primary.default.hex}}",
	})

	set_hl({
		"SnacksDashboardDesc",
		"SnacksDashboardIcon",
	}, {
		fg = "{{colors.on_surface_variant.default.hex}}",
	})

	set_hl({
		"SnacksDashboardKey",
		"SnacksDashboardSpecial",
	}, {
		fg = "{{colors.tertiary.default.hex}}",
	})

	set_hl({
		"SnacksDashboardDir",
	}, {
		fg = "{{colors.outline.default.hex}}",
	})
end

set_snacks_highlights()
vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "*",
	callback = set_snacks_highlights,
})

-- Mini.pick highlights
local function set_minipick_highlights()
	set_hl({ "MiniPickBorder" }, {
		fg = "{{colors.outline.default.hex}}",
		bg = "{{colors.background.default.hex}}",
	})

	set_hl({ "MiniPickBorderText", "MiniPickBorderBusy" }, {
		fg = "{{colors.primary.default.hex}}",
		bg = "{{colors.background.default.hex}}",
		bold = true,
	})

	set_hl({ "MiniPickNormal" }, {
		bg = "{{colors.surface_container_low.default.hex}}",
		fg = "{{colors.on_surface.default.hex}}",
	})

	set_hl({ "MiniPickPreview" }, {
		bg = "{{colors.surface_container_low.default.hex}}",
		fg = "{{colors.on_surface_variant.default.hex}}",
	})

	set_hl({ "MiniPickPreviewRegion" }, {
		bg = "{{colors.outline_variant.default.hex}}",
		fg = "{{colors.on_surface.default.hex}}",
	})

	set_hl({ "MiniPickPrompt" }, {
		fg = "{{colors.primary.default.hex}}",
		bg = "{{colors.background.default.hex}}",
	})

	set_hl({ "MiniPickMarked" }, {
		fg = "{{colors.primary.default.hex}}",
		bold = true,
	})

	set_hl({ "MiniPickMatch" }, {
		fg = "{{colors.primary.default.hex}}",
	})

	set_hl({ "MiniPickMatchRanges" }, {
		fg = "{{colors.tertiary.default.hex}}",
	})

	set_hl({ "MiniPickQuery" }, {
		fg = "{{colors.secondary.default.hex}}",
	})

	set_hl({ "MiniPickIcon" }, {
		fg = "{{colors.on_surface_variant.default.hex}}",
	})

	set_hl({ "MiniPickHeader" }, {
		fg = "{{colors.tertiary.default.hex}}",
		bold = true,
	})

	set_hl({ "MiniPickMatchCurrent" }, {
		fg = "{{colors.on_surface.default.hex}}",
		bg = "{{colors.outline_variant.default.hex}}",
		bold = true,
	})
end

-- Mini.files highlights
local function set_minifiles_highlights()
	set_hl({ "MiniFilesBorder" }, {
		fg = "{{colors.outline.default.hex}}",
		bg = "{{colors.background.default.hex}}",
	})

	set_hl({ "MiniFilesBorderModified" }, {
		fg = "{{colors.tertiary.default.hex}}",
		bg = "{{colors.background.default.hex}}",
	})

	set_hl({ "MiniFilesCursorLine" }, {
		bg = "{{colors.outline_variant.default.hex}}",
	})

	set_hl({ "MiniFilesDirectory" }, {
		fg = "{{colors.secondary.default.hex}}",
	})

	set_hl({ "MiniFilesFile" }, {
		fg = "{{colors.on_surface.default.hex}}",
	})

	set_hl({ "MiniFilesNormal" }, {
		bg = "{{colors.surface_container_low.default.hex}}",
		fg = "{{colors.on_surface.default.hex}}",
	})

	set_hl({ "MiniFilesTitle" }, {
		fg = "{{colors.outline.default.hex}}",
		bg = "{{colors.background.default.hex}}",
	})

	set_hl({ "MiniFilesTitleFocused" }, {
		fg = "{{colors.primary.default.hex}}",
		bg = "{{colors.background.default.hex}}",
		bold = true,
	})
end

set_minifiles_highlights()
vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "*",
	callback = set_minifiles_highlights,
})

set_minipick_highlights()
vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "*",
	callback = set_minipick_highlights,
})

-- Lualine theme
local lualine_theme = {
	normal = {
		a = {
			bg = "{{colors.primary_container.default.hex}}",
			fg = "{{colors.on_primary_container.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "{{colors.background.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
	},
	insert = {
		a = {
			bg = "{{colors.secondary_container.default.hex}}",
			fg = "{{colors.on_secondary_container.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "{{colors.background.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
	},
	visual = {
		a = {
			bg = "{{colors.tertiary_container.default.hex}}",
			fg = "{{colors.on_tertiary_container.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "{{colors.background.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
	},
	replace = {
		a = {
			bg = "{{colors.error_container.default.hex}}",
			fg = "{{colors.on_error_container.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "{{colors.background.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
	},
	command = {
		a = {
			bg = "{{colors.surface_variant.default.hex}}",
			fg = "{{colors.on_surface_variant.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "{{colors.background.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
	},
	inactive = {
		a = { bg = "{{colors.surface_container_low.default.hex}}", fg = "{{colors.outline.default.hex}}", gui = "bold" },
		b = { bg = "{{colors.surface_container_low.default.hex}}", fg = "{{colors.outline.default.hex}}" },
		c = { bg = "{{colors.background.default.hex}}", fg = "{{colors.outline.default.hex}}" },
	},
}

require("lualine").setup({
	options = {
		theme = lualine_theme,
	},
})
