-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "{{colors.background.default.hex}}",
	base01 = "{{colors.surface_container_lowest.default.hex}}",
	base02 = "{{colors.surface_container_low.default.hex}}",
	base03 = "{{colors.outline_variant.default.hex}}",
	base04 = "{{colors.on_surface_variant.default.hex}}",
	base05 = "{{colors.on_surface.default.hex}}",
	base06 = "{{colors.inverse_on_surface.default.hex}}",
	base07 = "{{colors.surface_bright.default.hex}}",

	base08 = "{{colors.tertiary.default.hex | lighten: -5}}",
	base09 = "{{colors.tertiary.default.hex}}",
	base0A = "{{colors.secondary.default.hex}}",
	base0B = "{{colors.primary.default.hex}}",
	base0C = "{{colors.tertiary_container.default.hex}}",
	base0D = "{{colors.primary_container.default.hex}}",
	base0E = "{{colors.secondary_container.default.hex}}",
	base0F = "{{colors.secondary.default.hex | lighten: -10}}",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "{{colors.tertiary.default.hex | lighten: -15.0 }}",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "{{colors.outline.default.hex}}",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "{{colors.tertiary.default.hex}}",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "{{colors.secondary.default.hex}}",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "{{colors.inverse_primary.default.hex}}",
})

local function set_transparent_bg(groups)
	for _, group in pairs(groups) do
		vim.api.nvim_set_hl(0, group, { bg = "NONE" })
	end
end

set_transparent_bg({
	"Normal",
	"NormalNC",
	"SignColumn",
	"LineNr",
	"EndOfBuffer",
	"StatusLine",
	"StatusLineNC",
	"lualine",
})

-- Bufferline (tab) colors - dynamically configure bufferline with matugen colors
local function set_bufferline_highlights()
	local ok, bufferline = pcall(require, "bufferline")
	if ok then
		bufferline.setup({
			highlights = {
				fill = { bg = "NONE", fg = "NONE" },
				background = { bg = "NONE", fg = "NONE" },
				buffer_visible = { bg = "NONE", fg = "NONE" },
				separator = { bg = "NONE", fg = "NONE" },
				buffer_selected = {
					bg = "{{colors.background.default.hex}}",
					fg = "{{colors.tertiary.default.hex}}",
					bold = true,
				},
			},
		})
	end
end

-- Run after plugins load and on ColorScheme changes
vim.defer_fn(set_bufferline_highlights, 100)
vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "*",
	callback = set_bufferline_highlights,
})

-- Snacks.nvim highlights - dynamically configure with matugen colors
local function set_snacks_highlights()
	set_hl_mutliple({
		"SnacksPicker",
		"SnacksPickerList",
		"SnacksPickerPreview",
		"SnacksPickerInput",
		"SnacksPickerBox",
	}, {
		bg = "NONE",
	})

	set_hl_mutliple({
		"SnacksPickerBorder",
		"SnacksPickerInputBorder",
		"SnacksPickerPreviewBorder",
		"SnacksPickerListBorder",
		"SnacksPickerBoxBorder",
	}, {
		fg = "{{colors.outline.default.hex}}",
		bg = "NONE",
	})

	-- Input window highlights (for explorer search)
	set_hl_mutliple({
		"SnacksInputNormal",
		"SnacksInput",
	}, {
		bg = "NONE",
		fg = "{{colors.on_surface.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksInputBorder",
		"SnacksPickerInputBorder",
	}, {
		fg = "{{colors.outline.default.hex}}",
		bg = "NONE",
	})

	set_hl_mutliple({
		"SnacksInputTitle",
		"SnacksPickerInputTitle",
	}, {
		fg = "{{colors.primary.default.hex}}",
		bg = "NONE",
	})

	set_hl_mutliple({
		"SnacksInputIcon",
	}, {
		fg = "{{colors.primary.default.hex}}",
	})

	-- Search-related highlights
	set_hl_mutliple({
		"SnacksPickerInputSearch",
	}, {
		fg = "{{colors.primary.default.hex}}",
	})

	-- Additional picker UI elements
	set_hl_mutliple({
		"SnacksPickerTotals",
		"SnacksPickerSpinner",
	}, {
		fg = "{{colors.outline.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksPickerLabel",
		"SnacksPickerSpecial",
	}, {
		fg = "{{colors.secondary.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksPickerSelected",
	}, {
		fg = "{{colors.primary.default.hex}}",
		bold = true,
	})

	set_hl_mutliple({
		"SnacksPickerPrompt",
		"SnacksPickerMatch",
	}, {
		fg = "{{colors.primary.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksPickerDir",
	}, {
		fg = "{{colors.on_surface_variant.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksIndent",
		"SnacksIndentBlank",
	}, {
		fg = "{{colors.outline_variant.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksIndentScope",
		"SnacksIndentChunk",
	}, {
		fg = "{{colors.primary.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksNotifierInfo",
		"SnacksNotifierTitleInfo",
		"SnacksNotifierIconInfo",
	}, {
		fg = "{{colors.primary.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksNotifierWarn",
		"SnacksNotifierTitleWarn",
		"SnacksNotifierIconWarn",
	}, {
		fg = "{{colors.tertiary.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksNotifierError",
		"SnacksNotifierTitleError",
		"SnacksNotifierIconError",
	}, {
		fg = "{{colors.error.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksNotifierDebug",
		"SnacksNotifierTitleDebug",
		"SnacksNotifierIconDebug",
	}, {
		fg = "{{colors.outline.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksNotifierTrace",
		"SnacksNotifierTitleTrace",
		"SnacksNotifierIconTrace",
	}, {
		fg = "{{colors.secondary.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksNotifierHistory",
		"SnacksNotifierHistoryTitle",
		"SnacksNotifierHistoryDateTime",
		"SnacksNotifierHistoryType",
	}, {
		fg = "{{colors.on_surface_variant.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksDashboardHeader",
		"SnacksDashboardFooter",
	}, {
		fg = "{{colors.primary.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksDashboardDesc",
		"SnacksDashboardIcon",
	}, {
		fg = "{{colors.on_surface_variant.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksDashboardKey",
		"SnacksDashboardSpecial",
	}, {
		fg = "{{colors.tertiary.default.hex}}",
	})

	set_hl_mutliple({
		"SnacksDashboardDir",
	}, {
		fg = "{{colors.outline.default.hex}}",
	})
end

-- Run immediately and on ColorScheme changes
set_snacks_highlights()
vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "*",
	callback = set_snacks_highlights,
})

-- Define custom lualine theme using matugen colors
local lualine_theme = {
	normal = {
		a = {
			bg = "{{colors.primary_container.default.hex}}",
			fg = "{{colors.on_primary_container.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "NONE", fg = "{{colors.on_surface.default.hex}}" },
	},
	insert = {
		a = {
			bg = "{{colors.secondary_container.default.hex}}",
			fg = "{{colors.on_secondary_container.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "NONE", fg = "{{colors.on_surface.default.hex}}" },
	},
	visual = {
		a = {
			bg = "{{colors.tertiary_container.default.hex}}",
			fg = "{{colors.on_tertiary_container.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "NONE", fg = "{{colors.on_surface.default.hex}}" },
	},
	replace = {
		a = {
			bg = "{{colors.error_container.default.hex}}",
			fg = "{{colors.on_error_container.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "NONE", fg = "{{colors.on_surface.default.hex}}" },
	},
	command = {
		a = {
			bg = "{{colors.surface_variant.default.hex}}",
			fg = "{{colors.on_surface_variant.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "NONE", fg = "{{colors.on_surface.default.hex}}" },
	},
	inactive = {
		a = { bg = "{{colors.surface_container_low.default.hex}}", fg = "{{colors.outline.default.hex}}", gui = "bold" },
		b = { bg = "{{colors.surface_container_low.default.hex}}", fg = "{{colors.outline.default.hex}}" },
		c = { bg = "NONE", fg = "{{colors.outline.default.hex}}" },
	},
}
-- Apply the theme to lualine
require("lualine").setup({
	options = {
		theme = lualine_theme,
	},
})
