-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "{{colors.background.default.hex}}",
	base01 = "{{colors.surface_container_lowest.default.hex}}",
	base02 = "{{colors.surface_container_low.default.hex}}",
	base03 = "{{colors.outline_variant.default.hex}}",
	base04 = "{{colors.on_surface_variant.default.hex}}",
	base05 = "{{colors.on_surface.default.hex}}",
	base06 = "{{colors.inverse_on_surface.default.hex}}",
	base07 = "{{colors.surface_bright.default.hex}}",

	base08 = "{{colors.tertiary.default.hex | lighten: -5}}",
	base09 = "{{colors.tertiary.default.hex}}",
	base0A = "{{colors.secondary.default.hex}}",
	base0B = "{{colors.primary.default.hex}}",
	base0C = "{{colors.tertiary_container.default.hex}}",
	base0D = "{{colors.primary_container.default.hex}}",
	base0E = "{{colors.secondary_container.default.hex}}",
	base0F = "{{colors.secondary.default.hex | lighten: -10}}",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "{{colors.primary_container.default.hex}}",
	fg = "{{colors.on_primary_container.default.hex}}", -- normal text contrast
})
-- After the base16-colorscheme setup
vim.api.nvim_set_hl(0, "Normal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "NONE" })

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "{{colors.tertiary.default.hex | lighten: -15.0 }}",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "{{colors.outline.default.hex}}",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "{{colors.tertiary.default.hex}}",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "{{colors.secondary.default.hex}}",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "{{colors.inverse_primary.default.hex}}",
})

local function set_transparent_bg(groups)
	for _, group in pairs(groups) do
		vim.api.nvim_set_hl(0, group, { bg = "NONE" })
	end
end

set_transparent_bg({
	"Normal",
	"NormalNC",
	"SignColumn",
	"LineNr",
	"EndOfBuffer",
	"StatusLine",
	"StatusLineNC",
	"lualine",
})

-- Bufferline (tab) colors
set_hl_mutliple({
	"BufferLineFill",
	"BufferLineBackground",
	"BufferLineBufferVisible",
	"BufferLineSeparator",
}, {
	bg = "NONE",
	fg = "NONE",
})

set_hl_mutliple({
	"BufferLineBufferSelected",
}, {
	bg = "{{colors.background.default.hex}}",
	fg = "{{colors.on_surface.default.hex}}",
	bold = true,
})

-- Define custom lualine theme using matugen colors
local lualine_theme = {
	normal = {
		a = {
			bg = "{{colors.primary_container.default.hex}}",
			fg = "{{colors.on_primary_container.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "NONE", fg = "{{colors.on_surface.default.hex}}" },
	},
	insert = {
		a = {
			bg = "{{colors.secondary_container.default.hex}}",
			fg = "{{colors.on_secondary_container.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "NONE", fg = "{{colors.on_surface.default.hex}}" },
	},
	visual = {
		a = {
			bg = "{{colors.tertiary_container.default.hex}}",
			fg = "{{colors.on_tertiary_container.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "NONE", fg = "{{colors.on_surface.default.hex}}" },
	},
	replace = {
		a = {
			bg = "{{colors.error_container.default.hex}}",
			fg = "{{colors.on_error_container.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "NONE", fg = "{{colors.on_surface.default.hex}}" },
	},
	command = {
		a = {
			bg = "{{colors.surface_variant.default.hex}}",
			fg = "{{colors.on_surface_variant.default.hex}}",
			gui = "bold",
		},
		b = { bg = "{{colors.surface_container.default.hex}}", fg = "{{colors.on_surface.default.hex}}" },
		c = { bg = "NONE", fg = "{{colors.on_surface.default.hex}}" },
	},
	inactive = {
		a = { bg = "{{colors.surface_container_low.default.hex}}", fg = "{{colors.outline.default.hex}}", gui = "bold" },
		b = { bg = "{{colors.surface_container_low.default.hex}}", fg = "{{colors.outline.default.hex}}" },
		c = { bg = "NONE", fg = "{{colors.outline.default.hex}}" },
	},
}
-- Apply the theme to lualine
require("lualine").setup({
	options = {
		theme = lualine_theme,
	},
})
