hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("systemctl --user start xdg-desktop-portal-hyprland.service")
	hl.exec_cmd("systemctl --user restart xdg-desktop-portal.service")
	hl.exec_cmd("quickcli > qscli_log.txt 2>&1")
	hl.exec_cmd("mpdris2-rs -n")
	hl.exec_cmd("mprisence")
	hl.exec_cmd("steam")
	hl.exec_cmd("qs -c reshell")
end)
