-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#111319",
	base01 = "#0c0e14",
	base02 = "#1a1b21",
	base03 = "#434652",
	base04 = "#c3c6d4",
	base05 = "#e2e2ea",
	base06 = "#2f3037",
	base07 = "#373940",

	base08 = "#ed96ff",
	base09 = "#f1afff",
	base0A = "#b8c5f1",
	base0B = "#b2c5ff",
	base0C = "#702b85",
	base0D = "#0f44a3",
	base0E = "#3b486d",
	base0F = "#8da2e9",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "#e463ff",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#8d909e",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#f1afff",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#b8c5f1",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#2e59b8",
})

local function set_transparent_bg(groups)
	for _, group in pairs(groups) do
		vim.api.nvim_set_hl(0, group, { bg = "NONE" })
	end
end

set_transparent_bg({
	"Normal",
	"NormalNC",
	"SignColumn",
	"LineNr",
	"EndOfBuffer",
	"StatusLine",
	"StatusLineNC",
	"lualine",
})

-- Bufferline (tab) colors - dynamically configure bufferline with matugen colors
local function set_bufferline_highlights()
	local ok, bufferline = pcall(require, "bufferline")
	if ok then
		bufferline.setup({
			highlights = {
				fill = { bg = "NONE", fg = "NONE" },
				background = { bg = "NONE", fg = "NONE" },
				buffer_visible = { bg = "NONE", fg = "NONE" },
				separator = { bg = "NONE", fg = "NONE" },
				buffer_selected = {
					bg = "#111319",
					fg = "#f1afff",
					bold = true,
				},
			},
		})
	end
end

-- Run after plugins load and on ColorScheme changes
vim.defer_fn(set_bufferline_highlights, 100)
vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "*",
	callback = set_bufferline_highlights,
})

-- Snacks.nvim highlights - dynamically configure with matugen colors
local function set_snacks_highlights()
	set_hl_mutliple({
		"SnacksPicker",
		"SnacksPickerList",
		"SnacksPickerPreview",
		"SnacksPickerInput",
		"SnacksPickerBox",
	}, {
		bg = "NONE",
	})

	set_hl_mutliple({
		"SnacksPickerBorder",
		"SnacksPickerInputBorder",
		"SnacksPickerPreviewBorder",
		"SnacksPickerListBorder",
		"SnacksPickerBoxBorder",
	}, {
		fg = "#8d909e",
		bg = "NONE",
	})

	-- Input window highlights (for explorer search)
	set_hl_mutliple({
		"SnacksInputNormal",
		"SnacksInput",
	}, {
		bg = "NONE",
		fg = "#e2e2ea",
	})

	set_hl_mutliple({
		"SnacksInputBorder",
		"SnacksPickerInputBorder",
	}, {
		fg = "#8d909e",
		bg = "NONE",
	})

	set_hl_mutliple({
		"SnacksInputTitle",
		"SnacksPickerInputTitle",
	}, {
		fg = "#b2c5ff",
		bg = "NONE",
	})

	set_hl_mutliple({
		"SnacksInputIcon",
	}, {
		fg = "#b2c5ff",
	})

	-- Search-related highlights
	set_hl_mutliple({
		"SnacksPickerInputSearch",
	}, {
		fg = "#b2c5ff",
	})

	-- Additional picker UI elements
	set_hl_mutliple({
		"SnacksPickerTotals",
		"SnacksPickerSpinner",
	}, {
		fg = "#8d909e",
	})

	set_hl_mutliple({
		"SnacksPickerLabel",
		"SnacksPickerSpecial",
	}, {
		fg = "#b8c5f1",
	})

	set_hl_mutliple({
		"SnacksPickerSelected",
	}, {
		fg = "#b2c5ff",
		bold = true,
	})

	set_hl_mutliple({
		"SnacksPickerPrompt",
		"SnacksPickerMatch",
	}, {
		fg = "#b2c5ff",
	})

	set_hl_mutliple({
		"SnacksPickerDir",
	}, {
		fg = "#c3c6d4",
	})

	set_hl_mutliple({
		"SnacksIndent",
		"SnacksIndentBlank",
	}, {
		fg = "#434652",
	})

	set_hl_mutliple({
		"SnacksIndentScope",
		"SnacksIndentChunk",
	}, {
		fg = "#b2c5ff",
	})

	set_hl_mutliple({
		"SnacksNotifierInfo",
		"SnacksNotifierTitleInfo",
		"SnacksNotifierIconInfo",
	}, {
		fg = "#b2c5ff",
	})

	set_hl_mutliple({
		"SnacksNotifierWarn",
		"SnacksNotifierTitleWarn",
		"SnacksNotifierIconWarn",
	}, {
		fg = "#f1afff",
	})

	set_hl_mutliple({
		"SnacksNotifierError",
		"SnacksNotifierTitleError",
		"SnacksNotifierIconError",
	}, {
		fg = "#ffb4ab",
	})

	set_hl_mutliple({
		"SnacksNotifierDebug",
		"SnacksNotifierTitleDebug",
		"SnacksNotifierIconDebug",
	}, {
		fg = "#8d909e",
	})

	set_hl_mutliple({
		"SnacksNotifierTrace",
		"SnacksNotifierTitleTrace",
		"SnacksNotifierIconTrace",
	}, {
		fg = "#b8c5f1",
	})

	set_hl_mutliple({
		"SnacksNotifierHistory",
		"SnacksNotifierHistoryTitle",
		"SnacksNotifierHistoryDateTime",
		"SnacksNotifierHistoryType",
	}, {
		fg = "#c3c6d4",
	})

	set_hl_mutliple({
		"SnacksDashboardHeader",
		"SnacksDashboardFooter",
	}, {
		fg = "#b2c5ff",
	})

	set_hl_mutliple({
		"SnacksDashboardDesc",
		"SnacksDashboardIcon",
	}, {
		fg = "#c3c6d4",
	})

	set_hl_mutliple({
		"SnacksDashboardKey",
		"SnacksDashboardSpecial",
	}, {
		fg = "#f1afff",
	})

	set_hl_mutliple({
		"SnacksDashboardDir",
	}, {
		fg = "#8d909e",
	})
end

-- Run immediately and on ColorScheme changes
set_snacks_highlights()
vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "*",
	callback = set_snacks_highlights,
})

-- Define custom lualine theme using matugen colors
local lualine_theme = {
	normal = {
		a = {
			bg = "#0f44a3",
			fg = "#dfe5ff",
			gui = "bold",
		},
		b = { bg = "#1e1f26", fg = "#e2e2ea" },
		c = { bg = "NONE", fg = "#e2e2ea" },
	},
	insert = {
		a = {
			bg = "#3b486d",
			fg = "#dce3ff",
			gui = "bold",
		},
		b = { bg = "#1e1f26", fg = "#e2e2ea" },
		c = { bg = "NONE", fg = "#e2e2ea" },
	},
	visual = {
		a = {
			bg = "#702b85",
			fg = "#fcdcff",
			gui = "bold",
		},
		b = { bg = "#1e1f26", fg = "#e2e2ea" },
		c = { bg = "NONE", fg = "#e2e2ea" },
	},
	replace = {
		a = {
			bg = "#93000a",
			fg = "#ffdad6",
			gui = "bold",
		},
		b = { bg = "#1e1f26", fg = "#e2e2ea" },
		c = { bg = "NONE", fg = "#e2e2ea" },
	},
	command = {
		a = {
			bg = "#434652",
			fg = "#c3c6d4",
			gui = "bold",
		},
		b = { bg = "#1e1f26", fg = "#e2e2ea" },
		c = { bg = "NONE", fg = "#e2e2ea" },
	},
	inactive = {
		a = { bg = "#1a1b21", fg = "#8d909e", gui = "bold" },
		b = { bg = "#1a1b21", fg = "#8d909e" },
		c = { bg = "NONE", fg = "#8d909e" },
	},
}
-- Apply the theme to lualine
require("lualine").setup({
	options = {
		theme = lualine_theme,
	},
})
