-- Generated by Matugen

require("base16-colorscheme").setup({
  base00 = "#1e0f14",
  base01 = "#180a0f",
  base02 = "#27171c",
  base03 = "#5a3f48",
  base04 = "#e2bdc7",
  base05 = "#f9dbe2",
  base06 = "#3e2b31",
  base07 = "#47343a",

  base08 = "#ff9f8a",
  base09 = "#ffb4a3",
  base0A = "#ffb0ca",
  base0B = "#ffb0ca",
  base0C = "#ff562e",
  base0D = "#ff479a",
  base0E = "#8a184f",
  base0F = "#ff7da8",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
  bg = "#ff479a",
  fg = "#000000", -- normal text contrast
})
-- After the base16-colorscheme setup
vim.api.nvim_set_hl(0, "Normal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "NONE" })

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
  fg = "#ff7657",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
  fg = "#a98891",
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
  fg = "#ffb4a3",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
  fg = "#ffb0ca",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
  fg = "#b90067",
})

local function set_transparent_bg(groups)
  for _, group in pairs(groups) do
    vim.api.nvim_set_hl(0, group, { bg = "NONE" })
  end
end
set_transparent_bg({
  "Normal",
  "NormalNC",
  "SignColumn",
  "LineNr",
  "EndOfBuffer",
  "StatusLine",
  "StatusLineNC",
})
