-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#1e0f14",
	base01 = "#180a0f",
	base02 = "#27171c",
	base03 = "#5a3f48",
	base04 = "#e2bdc7",
	base05 = "#f9dbe2",
	base06 = "#3e2b31",
	base07 = "#47343a",

	base08 = "#ff9f8a",
	base09 = "#ffb4a3",
	base0A = "#ffb0ca",
	base0B = "#ffb0ca",
	base0C = "#ff562e",
	base0D = "#ff479a",
	base0E = "#8a184f",
	base0F = "#ff7da8",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#ff479a",
	fg = "#000000", -- normal text contrast
})
-- After the base16-colorscheme setup
vim.api.nvim_set_hl(0, "Normal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "NONE" })

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "#ff7657",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#a98891",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#ffb4a3",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#ffb0ca",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#b90067",
})

local function set_transparent_bg(groups)
	for _, group in pairs(groups) do
		vim.api.nvim_set_hl(0, group, { bg = "NONE" })
	end
end

set_transparent_bg({
	"Normal",
	"NormalNC",
	"SignColumn",
	"LineNr",
	"EndOfBuffer",
	"StatusLine",
	"StatusLineNC",
	"lualine",
})

-- Bufferline (tab) colors
set_hl_mutliple({
	"BufferLineFill",
	"BufferLineBackground",
	"BufferLineBufferVisible",
	"BufferLineSeparator",
}, {
	bg = "NONE",
	fg = "NONE",
})

set_hl_mutliple({
	"BufferLineBufferSelected",
}, {
	bg = "#1e0f14",
	fg = "#f9dbe2",
	bold = true,
})

-- Define custom lualine theme using matugen colors
local lualine_theme = {
	normal = {
		a = {
			bg = "#ff479a",
			fg = "#000000",
			gui = "bold",
		},
		b = { bg = "#2b1b20", fg = "#f9dbe2" },
		c = { bg = "NONE", fg = "#f9dbe2" },
	},
	insert = {
		a = {
			bg = "#8a184f",
			fg = "#ffdbe4",
			gui = "bold",
		},
		b = { bg = "#2b1b20", fg = "#f9dbe2" },
		c = { bg = "NONE", fg = "#f9dbe2" },
	},
	visual = {
		a = {
			bg = "#ff562e",
			fg = "#000000",
			gui = "bold",
		},
		b = { bg = "#2b1b20", fg = "#f9dbe2" },
		c = { bg = "NONE", fg = "#f9dbe2" },
	},
	replace = {
		a = {
			bg = "#93000a",
			fg = "#ffdad6",
			gui = "bold",
		},
		b = { bg = "#2b1b20", fg = "#f9dbe2" },
		c = { bg = "NONE", fg = "#f9dbe2" },
	},
	command = {
		a = {
			bg = "#5a3f48",
			fg = "#e2bdc7",
			gui = "bold",
		},
		b = { bg = "#2b1b20", fg = "#f9dbe2" },
		c = { bg = "NONE", fg = "#f9dbe2" },
	},
	inactive = {
		a = { bg = "#27171c", fg = "#a98891", gui = "bold" },
		b = { bg = "#27171c", fg = "#a98891" },
		c = { bg = "NONE", fg = "#a98891" },
	},
}
-- Apply the theme to lualine
require("lualine").setup({
	options = {
		theme = lualine_theme,
	},
})
