-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#191206",
	base01 = "#140d03",
	base02 = "#221a0d",
	base03 = "#54442a",
	base04 = "#dac3a0",
	base05 = "#f0e0ca",
	base06 = "#382f20",
	base07 = "#413828",

	base08 = "#ebb556",
	base09 = "#eebf6d",
	base0A = "#ffb4a3",
	base0B = "#ffb4a3",
	base0C = "#5e4200",
	base0D = "#7d2c1a",
	base0E = "#733426",
	base0F = "#ff8a70",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "#e6a128",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#a28e6e",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#eebf6d",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#ffb4a3",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#9c432f",
})

local function set_transparent_bg(groups)
	for _, group in pairs(groups) do
		vim.api.nvim_set_hl(0, group, { bg = "NONE" })
	end
end

set_transparent_bg({
	"Normal",
	"NormalNC",
	"SignColumn",
	"LineNr",
	"EndOfBuffer",
	"StatusLine",
	"StatusLineNC",
	"lualine",
})

-- Bufferline (tab) colors - dynamically configure bufferline with matugen colors
local function set_bufferline_highlights()
	local ok, bufferline = pcall(require, "bufferline")
	if ok then
		bufferline.setup({
			highlights = {
				fill = { bg = "NONE", fg = "NONE" },
				background = { bg = "NONE", fg = "NONE" },
				buffer_visible = { bg = "NONE", fg = "NONE" },
				separator = { bg = "NONE", fg = "NONE" },
				buffer_selected = {
					bg = "#191206",
					fg = "#eebf6d",
					bold = true,
				},
			},
		})
	end
end

-- Run after plugins load and on ColorScheme changes
vim.defer_fn(set_bufferline_highlights, 100)
vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "*",
	callback = set_bufferline_highlights,
})

-- Snacks.nvim highlights - dynamically configure with matugen colors
local function set_snacks_highlights()
	set_hl_mutliple({
		"SnacksPicker",
		"SnacksPickerList",
		"SnacksPickerPreview",
		"SnacksPickerInput",
		"SnacksPickerBox",
	}, {
		bg = "NONE",
	})

	set_hl_mutliple({
		"SnacksPickerBorder",
		"SnacksPickerInputBorder",
		"SnacksPickerPreviewBorder",
		"SnacksPickerListBorder",
		"SnacksPickerBoxBorder",
	}, {
		fg = "#a28e6e",
		bg = "NONE",
	})

	-- Input window highlights (for explorer search)
	set_hl_mutliple({
		"SnacksInputNormal",
		"SnacksInput",
	}, {
		bg = "NONE",
		fg = "#f0e0ca",
	})

	set_hl_mutliple({
		"SnacksInputBorder",
		"SnacksPickerInputBorder",
	}, {
		fg = "#a28e6e",
		bg = "NONE",
	})

	set_hl_mutliple({
		"SnacksInputTitle",
		"SnacksPickerInputTitle",
	}, {
		fg = "#ffb4a3",
		bg = "NONE",
	})

	set_hl_mutliple({
		"SnacksInputIcon",
	}, {
		fg = "#ffb4a3",
	})

	-- Search-related highlights
	set_hl_mutliple({
		"SnacksPickerInputSearch",
	}, {
		fg = "#ffb4a3",
	})

	-- Additional picker UI elements
	set_hl_mutliple({
		"SnacksPickerTotals",
		"SnacksPickerSpinner",
	}, {
		fg = "#a28e6e",
	})

	set_hl_mutliple({
		"SnacksPickerLabel",
		"SnacksPickerSpecial",
	}, {
		fg = "#ffb4a3",
	})

	set_hl_mutliple({
		"SnacksPickerSelected",
	}, {
		fg = "#ffb4a3",
		bold = true,
	})

	set_hl_mutliple({
		"SnacksPickerPrompt",
		"SnacksPickerMatch",
	}, {
		fg = "#ffb4a3",
	})

	set_hl_mutliple({
		"SnacksPickerDir",
	}, {
		fg = "#dac3a0",
	})

	set_hl_mutliple({
		"SnacksIndent",
		"SnacksIndentBlank",
	}, {
		fg = "#54442a",
	})

	set_hl_mutliple({
		"SnacksIndentScope",
		"SnacksIndentChunk",
	}, {
		fg = "#ffb4a3",
	})

	set_hl_mutliple({
		"SnacksNotifierInfo",
		"SnacksNotifierTitleInfo",
		"SnacksNotifierIconInfo",
	}, {
		fg = "#ffb4a3",
	})

	set_hl_mutliple({
		"SnacksNotifierWarn",
		"SnacksNotifierTitleWarn",
		"SnacksNotifierIconWarn",
	}, {
		fg = "#eebf6d",
	})

	set_hl_mutliple({
		"SnacksNotifierError",
		"SnacksNotifierTitleError",
		"SnacksNotifierIconError",
	}, {
		fg = "#ffb4ab",
	})

	set_hl_mutliple({
		"SnacksNotifierDebug",
		"SnacksNotifierTitleDebug",
		"SnacksNotifierIconDebug",
	}, {
		fg = "#a28e6e",
	})

	set_hl_mutliple({
		"SnacksNotifierTrace",
		"SnacksNotifierTitleTrace",
		"SnacksNotifierIconTrace",
	}, {
		fg = "#ffb4a3",
	})

	set_hl_mutliple({
		"SnacksNotifierHistory",
		"SnacksNotifierHistoryTitle",
		"SnacksNotifierHistoryDateTime",
		"SnacksNotifierHistoryType",
	}, {
		fg = "#dac3a0",
	})

	set_hl_mutliple({
		"SnacksDashboardHeader",
		"SnacksDashboardFooter",
	}, {
		fg = "#ffb4a3",
	})

	set_hl_mutliple({
		"SnacksDashboardDesc",
		"SnacksDashboardIcon",
	}, {
		fg = "#dac3a0",
	})

	set_hl_mutliple({
		"SnacksDashboardKey",
		"SnacksDashboardSpecial",
	}, {
		fg = "#eebf6d",
	})

	set_hl_mutliple({
		"SnacksDashboardDir",
	}, {
		fg = "#a28e6e",
	})
end

-- Run immediately and on ColorScheme changes
set_snacks_highlights()
vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "*",
	callback = set_snacks_highlights,
})

-- Mini.pick highlights - dynamically configure with matugen colors
local function set_minipick_highlights()
	set_hl_mutliple({
		"MiniPickBorder",
	}, {
		fg = "#a28e6e",
		bg = "NONE",
	})

	set_hl_mutliple({
		"MiniPickBorderText",
		"MiniPickBorderBusy",
	}, {
		fg = "#ffb4a3",
		bg = "NONE",
		bold = true,
	})

	set_hl_mutliple({
		"MiniPickNormal",
	}, {
		bg = "NONE",
		fg = "#f0e0ca",
	})

	set_hl_mutliple({
		"MiniPickPreview",
	}, {
		bg = "#221a0d",
		fg = "#dac3a0",
	})

	set_hl_mutliple({
		"MiniPickPreviewRegion",
	}, {
		bg = "#54442a",
		fg = "#f0e0ca",
	})

	set_hl_mutliple({
		"MiniPickPrompt",
	}, {
		fg = "#ffb4a3",
		bg = "NONE",
	})

	set_hl_mutliple({
		"MiniPickMarked",
	}, {
		fg = "#ffb4a3",
		bold = true,
	})

	set_hl_mutliple({
		"MiniPickMatch",
	}, {
		fg = "#ffb4a3",
	})

	set_hl_mutliple({
		"MiniPickMatchRanges",
	}, {
		fg = "#eebf6d",
	})

	set_hl_mutliple({
		"MiniPickQuery",
	}, {
		fg = "#ffb4a3",
	})

	set_hl_mutliple({
		"MiniPickIcon",
	}, {
		fg = "#dac3a0",
	})

	set_hl_mutliple({
		"MiniPickHeader",
	}, {
		fg = "#eebf6d",
		bold = true,
	})

	set_hl_mutliple({
		"MiniPickMatchCurrent",
	}, {
		fg = "#f0e0ca",
		bg = "#54442a",
		bold = true,
	})
end

-- Run immediately and on ColorScheme changes
set_minipick_highlights()
vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "*",
	callback = set_minipick_highlights,
})

-- Define custom lualine theme using matugen colors
local lualine_theme = {
	normal = {
		a = {
			bg = "#7d2c1a",
			fg = "#ffdad2",
			gui = "bold",
		},
		b = { bg = "#261e11", fg = "#f0e0ca" },
		c = { bg = "NONE", fg = "#f0e0ca" },
	},
	insert = {
		a = {
			bg = "#733426",
			fg = "#ffdad2",
			gui = "bold",
		},
		b = { bg = "#261e11", fg = "#f0e0ca" },
		c = { bg = "NONE", fg = "#f0e0ca" },
	},
	visual = {
		a = {
			bg = "#5e4200",
			fg = "#ffdea8",
			gui = "bold",
		},
		b = { bg = "#261e11", fg = "#f0e0ca" },
		c = { bg = "NONE", fg = "#f0e0ca" },
	},
	replace = {
		a = {
			bg = "#93000a",
			fg = "#ffdad6",
			gui = "bold",
		},
		b = { bg = "#261e11", fg = "#f0e0ca" },
		c = { bg = "NONE", fg = "#f0e0ca" },
	},
	command = {
		a = {
			bg = "#54442a",
			fg = "#dac3a0",
			gui = "bold",
		},
		b = { bg = "#261e11", fg = "#f0e0ca" },
		c = { bg = "NONE", fg = "#f0e0ca" },
	},
	inactive = {
		a = { bg = "#221a0d", fg = "#a28e6e", gui = "bold" },
		b = { bg = "#221a0d", fg = "#a28e6e" },
		c = { bg = "NONE", fg = "#a28e6e" },
	},
}
-- Apply the theme to lualine
require("lualine").setup({
	options = {
		theme = lualine_theme,
	},
})
